name: Scan GitHub Actions

"on":
  pull_request:

permissions: {}

jobs:
  scan:
    name: Scan GitHub Actions
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@bce53819ffa60fcdf8f0f349686d807e5a66a71b
    permissions:
      actions: read
      contents: read
      id-token: write
